openapi: 3.0.0
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
- url: /
paths:
  /:
    get:
      tags:
      - index
      summary: Returns hello world page.
      operationId: rootGET
      responses:
        "200":
          description: OK
      x-swagger-router-controller: Index
  /hash:
    post:
      tags:
      - hash
      summary: Returns hash
      operationId: hashPOST
      requestBody:
        description: Data string for hashing
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
        required: true
      responses:
        "200":
          description: Hash object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-swagger-router-controller: Hash
  /vhash:
    post:
      tags:
      - hash
      summary: Checkes integrity of data
      operationId: vhashPOST
      requestBody:
        description: Data string for hashing
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_1'
        required: true
      responses:
        "200":
          description: returns status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
      x-swagger-router-controller: Hash
components:
  schemas:
    body:
      type: object
      properties:
        data:
          type: string
          description: raw string
    inline_response_200:
      type: object
      properties:
        hash:
          type: string
          description: hashed string
      example:
        hash: hash
    body_1:
      type: object
      properties:
        data:
          type: string
          description: base64 string of raw data
        hash:
          type: string
          description: hash of data
    inline_response_200_1:
      type: object
      properties:
        status:
          type: integer
          description: status code (0 if data is integral; 1 if not)
      example:
        status: 0
